// <auto-generated />
using System;
using FantasyX.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyX.Backend.Migrations
{
    [DbContext(typeof(FantasyXDbContext))]
    [Migration("20261006000640_AddPlayerRankingSnapshots")]
    partial class AddPlayerRankingSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyX.Backend.Models.PlayerRankingSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FirstWeek")
                        .HasColumnType("integer")
                        .HasColumnName("first_week");

                    b.Property<int>("LastWeek")
                        .HasColumnType("integer")
                        .HasColumnName("last_week");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_id");

                    b.Property<string>("ProjectionSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("projection_source");

                    b.Property<string>("ReplacementLevels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("replacement_levels");

                    b.Property<int>("ScoringPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_period");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Season", "ScoringPeriod", "ProjectionSource")
                        .IsUnique()
                        .HasDatabaseName("ix_player_ranking_snapshots_key");

                    b.ToTable("player_ranking_snapshots", (string)null);
                });

            modelBuilder.Entity("FantasyX.Backend.Models.PlayerRankingSnapshotEntry", b =>
                {
                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int?>("FantasyTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("fantasy_team_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<int>("PositionRank")
                        .HasColumnType("integer")
                        .HasColumnName("position_rank");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<double>("RestOfSeasonPoints")
                        .HasColumnType("double precision")
                        .HasColumnName("rest_of_season_points");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<string>("WeeklyProjections")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weekly_projections");

                    b.HasKey("SnapshotId", "PlayerId");

                    b.ToTable("player_ranking_snapshot_entries", (string)null);
                });

            modelBuilder.Entity("FantasyX.Backend.Models.SavedCredentials", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("EncryptedEspnS2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_espn_s2");

                    b.Property<string>("EncryptedSwid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_swid");

                    b.Property<long?>("LastLeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_league_id");

                    b.Property<int?>("LastSeason")
                        .HasColumnType("integer")
                        .HasColumnName("last_season");

                    b.Property<int?>("LastTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("last_team_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DeviceId");

                    b.ToTable("saved_credentials", (string)null);
                });

            modelBuilder.Entity("FantasyX.Backend.Models.PlayerRankingSnapshotEntry", b =>
                {
                    b.HasOne("FantasyX.Backend.Models.PlayerRankingSnapshot", null)
                        .WithMany("Entries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_ranking_snapshot_entries_snapshot");
                });

            modelBuilder.Entity("FantasyX.Backend.Models.PlayerRankingSnapshot", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
