// <auto-generated />
using System;
using FantasyX.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyX.Backend.Migrations
{
    [DbContext(typeof(FantasyXDbContext))]
    partial class FantasyXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyX.Backend.Models.SavedCredentials", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("EncryptedEspnS2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_espn_s2");

                    b.Property<string>("EncryptedSwid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_swid");

                    b.Property<long?>("LastLeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_league_id");

                    b.Property<int?>("LastSeason")
                        .HasColumnType("integer")
                        .HasColumnName("last_season");

                    b.Property<int?>("LastTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("last_team_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DeviceId");

                    b.ToTable("saved_credentials", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
